-- schema.sql  --  relational model for PPMS
-- Company is implicit (single tenant). Read-only seed data is generated by
-- build_db.py; live changes during a session are kept in a localStorage
-- overlay and merged by src/data/repository.js.

PRAGMA foreign_keys = ON;

CREATE TABLE site (
    id          TEXT PRIMARY KEY,     -- 'VND'
    name        TEXT NOT NULL,        -- 'Vindhya'
    state       TEXT,
    region      TEXT,
    capacity_mw INTEGER
);

CREATE TABLE unit (
    id       TEXT PRIMARY KEY,        -- 'VND-U1'
    site_id  TEXT NOT NULL REFERENCES site(id),
    name     TEXT NOT NULL,           -- 'Unit 1'
    capacity_mw INTEGER
);

CREATE TABLE department (
    id   TEXT PRIMARY KEY,            -- 'BLR'
    name TEXT NOT NULL                -- 'Boiler'
);

CREATE TABLE equipment (
    id         TEXT PRIMARY KEY,      -- 'VND-U2-CONDENSER'
    unit_id    TEXT NOT NULL REFERENCES unit(id),
    dept_id    TEXT NOT NULL REFERENCES department(id),
    ekey       TEXT NOT NULL,         -- 'CONDENSER'
    label      TEXT NOT NULL          -- 'Condenser'
);

-- demo users. password is a PLAINTEXT demo credential shown on the login
-- screen; this is NOT secure auth and must never be described as such.
CREATE TABLE app_user (
    id         TEXT PRIMARY KEY,      -- 'u_corp_1'
    name       TEXT NOT NULL,
    email      TEXT NOT NULL,
    role       TEXT NOT NULL,         -- 'corporate' | 'plant'
    site_id    TEXT REFERENCES site(id),        -- null for corporate (all sites)
    dept_id    TEXT REFERENCES department(id),  -- null for corporate
    title      TEXT,                  -- 'Performance Analytics Engineer'
    password   TEXT NOT NULL          -- demo only
);

CREATE TABLE kpi_definition (
    kpi_key      TEXT PRIMARY KEY,    -- 'gross_heat_rate'
    label        TEXT NOT NULL,
    unit         TEXT,
    benchmark    REAL,
    direction    TEXT,                -- 'lower' | 'higher' (which is better)
    critical_pct REAL,                -- deviation fraction -> Critical severity
    dept_id      TEXT REFERENCES department(id)   -- default owning department
);

-- daily KPI series per unit
CREATE TABLE kpi_reading (
    site_id   TEXT NOT NULL REFERENCES site(id),
    unit_id   TEXT NOT NULL REFERENCES unit(id),
    kpi_key   TEXT NOT NULL REFERENCES kpi_definition(kpi_key),
    ts        INTEGER NOT NULL,       -- epoch seconds (day granularity)
    value     REAL NOT NULL,
    benchmark REAL NOT NULL
);
CREATE INDEX idx_kpi_reading ON kpi_reading(unit_id, kpi_key, ts);

-- issues (the workflow core). Seed rows here; new/edited rows live in overlay.
CREATE TABLE issue (
    id              TEXT PRIMARY KEY,     -- 'ISS-0001'
    site_id         TEXT NOT NULL REFERENCES site(id),
    unit_id         TEXT REFERENCES unit(id),
    dept_id         TEXT NOT NULL REFERENCES department(id),
    equipment_id    TEXT REFERENCES equipment(id),
    kpi_key         TEXT REFERENCES kpi_definition(kpi_key),
    severity        TEXT NOT NULL,        -- 'Low'|'Medium'|'High'|'Critical'
    title           TEXT NOT NULL,
    observation     TEXT,
    benchmark_value REAL,
    actual_value    REAL,
    deviation       REAL,
    impact_generation TEXT,               -- e.g. 'approx 12 MU/month at risk'
    target_date     INTEGER,              -- epoch seconds
    created_by      TEXT NOT NULL REFERENCES app_user(id),
    created_at      INTEGER NOT NULL,
    status          TEXT NOT NULL,        -- see state machine
    progress_pct    INTEGER DEFAULT 0,
    escalation_level INTEGER DEFAULT 0,
    closed_at       INTEGER
);
CREATE INDEX idx_issue_dept ON issue(site_id, dept_id, status);

-- plant responses (RCA / actions) attached to an issue
CREATE TABLE issue_response (
    id                TEXT PRIMARY KEY,
    issue_id          TEXT NOT NULL REFERENCES issue(id),
    user_id           TEXT NOT NULL REFERENCES app_user(id),
    root_cause        TEXT,
    action_taken      TEXT,
    preventive_action TEXT,
    expected_completion INTEGER,
    status            TEXT,               -- status the response set the issue to
    created_at        INTEGER NOT NULL
);

CREATE TABLE issue_comment (
    id         TEXT PRIMARY KEY,
    issue_id   TEXT NOT NULL REFERENCES issue(id),
    user_id    TEXT NOT NULL REFERENCES app_user(id),
    body       TEXT,
    created_at INTEGER NOT NULL
);

-- attachments stored as base64 (size-capped in the UI)
CREATE TABLE issue_attachment (
    id         TEXT PRIMARY KEY,
    issue_id   TEXT NOT NULL REFERENCES issue(id),
    user_id    TEXT NOT NULL REFERENCES app_user(id),
    filename   TEXT,
    mime       TEXT,
    size_bytes INTEGER,
    data_b64   TEXT,
    created_at INTEGER NOT NULL
);

-- immutable audit log. NO delete path is exposed anywhere in the app code.
CREATE TABLE audit_log (
    id         TEXT PRIMARY KEY,
    entity     TEXT NOT NULL,          -- 'issue'
    entity_id  TEXT NOT NULL,
    user_id    TEXT,
    ts         INTEGER NOT NULL,
    field      TEXT,                   -- what changed ('status','progress_pct',...)
    old_value  TEXT,
    new_value  TEXT,
    comment    TEXT
);
CREATE INDEX idx_audit_entity ON audit_log(entity, entity_id, ts);

-- configurable SLA / escalation rules
CREATE TABLE sla_rule (
    days_pending INTEGER PRIMARY KEY,
    level        INTEGER NOT NULL,
    role         TEXT NOT NULL,
    label        TEXT
);

-- notifications (in-app + simulated "email outbox")
CREATE TABLE notification (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES app_user(id),
    issue_id   TEXT REFERENCES issue(id),
    kind       TEXT,                   -- 'assigned'|'escalation'|'closed'|'info'
    channel    TEXT,                   -- 'inapp'|'email'
    subject    TEXT,
    body       TEXT,
    read       INTEGER DEFAULT 0,
    ts         INTEGER NOT NULL
);

-- lightweight metadata (schema version, generation date, virtual 'today')
CREATE TABLE meta (
    key   TEXT PRIMARY KEY,
    value TEXT
);
